# Form implementation generated from reading ui file 'listItem.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 171)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(530, 0))
        self.frame.setMaximumSize(QtCore.QSize(530, 551))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: white; \n"
"    border-radius : 10\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(0, 10, 91, 81))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.imageAvatar = QtWidgets.QLabel(parent=self.frame_2)
        self.imageAvatar.setGeometry(QtCore.QRect(13, 3, 65, 71))
        self.imageAvatar.setStyleSheet("")
        self.imageAvatar.setText("")
        self.imageAvatar.setPixmap(QtGui.QPixmap("respresso/ios/RespressoImages.xcassets/images.imageset/images.png"))
        self.imageAvatar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageAvatar.setObjectName("imageAvatar")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.lblCode = QtWidgets.QLabel(parent=self.frame_4)
        self.lblCode.setGeometry(QtCore.QRect(10, 50, 121, 31))
        self.lblCode.setStyleSheet("")
        self.lblCode.setObjectName("lblCode")
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_7.setGeometry(QtCore.QRect(0, 20, 111, 51))
        self.frame_7.setAutoFillBackground(False)
        self.frame_7.setStyleSheet("QFrame {\n"
"    border-radius: 23;    \n"
"    background-color: green; \n"
"    color : white\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(80, 10, 21, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("tick-circle.png"))
        self.label_6.setObjectName("label_6")
        self.checkInTime = QtWidgets.QLabel(parent=self.frame_7)
        self.checkInTime.setGeometry(QtCore.QRect(20, 10, 54, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.checkInTime.setFont(font)
        self.checkInTime.setStyleSheet("")
        self.checkInTime.setObjectName("checkInTime")
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame)
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_6.setObjectName("frame_6")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_8.setGeometry(QtCore.QRect(0, 20, 111, 51))
        self.frame_8.setAutoFillBackground(False)
        self.frame_8.setStyleSheet("QFrame {\n"
"    border-radius: 23;    \n"
"    background-color: blue; \n"
"    color : white\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.checkOutTime = QtWidgets.QLabel(parent=self.frame_8)
        self.checkOutTime.setGeometry(QtCore.QRect(20, 10, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.checkOutTime.setFont(font)
        self.checkOutTime.setStyleSheet("")
        self.checkOutTime.setObjectName("checkOutTime")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(80, 10, 21, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("tick-circle.png"))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Bùi Bé Tư"))
        self.lblCode.setText(_translate("MainWindow", "Mã NV: 12321312"))
        self.checkInTime.setText(_translate("MainWindow", "08:00"))
        self.checkOutTime.setText(_translate("MainWindow", "08:00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
